{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "goldpinger.fullname" . }}-clusterrolebinding
  labels:
    {{- include "goldpinger.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "goldpinger.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "goldpinger.fullname" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
{{- end }}
